---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-minio-credentials
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgCTUysYK1PaRP1qZekbUPHHKL9Qr23IkC4bcsTQJwBvVh2TZa1kYhTeviCxdf/aOBl3zl/SSnJQ8EKpUlYjItHvx2kC+ff+ugEu0R0sXoKatV90KZweBuVbIlTlRV9OSXe2TVKLB4QkjyOPUi6CEIx9awOhXHLADViTcZVSa8SCpreFpRJSKy61XQAOthtaq0LuV9+za3tcsZO+ja9i7CDgGVqx12EctnXMQ7PmGoJcz6I1byn5lxkYfpT9w8/KmyUJ1R1ZnnWZUAc4+9jk5/nQB8cbqvD+eOWhC4K7Q4bTXPo2u9hx6drkf69c+0mUtBBvgih27KmxAZk5DegHaA0BeecLngvYzKKkjj/fyio+1Pfd+lg3/pPizU+1OuVzsUn1anMHpxlJjB2Gp7d9heMKaj3TrQcyV61fLzAfFFf2QxsDcQ6tswVtt+rETYCxQtE7Yaazivat7zWJ3ZK2AJkByN1jn+IOl3kGh3Q8arIgSwgKoonaIlTkDgRLn/Qo14tQPWIZ08ODuG16LY6O7+T7HBTvClI+vG0PiXbyr4irTSiprKLELw1RQViaKxMi9NMDBnUQPqD+2nHImtVeiteRnRj/K2NZiX9uBVTWbAtIQwZb7rsuS4BprkRHhke5R6Ksuj94myAP7h+ErwUBoic4fPxbO/8jyiNHBfvDcpsW/c92eh7D5Yu4Rz0elZDIIIg4zVRP3tnI58dD+qPRV3P8
    secretkey: AgAJ22mhQBBBO7L6hEjsCD0h8HY55UiQXQhAlRPMwyiCW5/HFOR5AvPatEynYFmXBvzILni583/DsGUtcfD5Hmznp3CJnlhFLCZ+6EX1p9gE0xEdXPazVHsxsSZ49+n7c0ECB8eoxR+NKyfwO7sJPF45Era+GmgupXOc1crmYku1ROUXK9Ju5TfoYa5KsxkBc1HPO6W4o/c2P6hHvC3r54+N/MyaipmumanWXmzW+hwxYi5AJhImxZehj80C6z//tDzub9P8L0p+013amAGpDHKCIwfXBS2jBc60YDwXRQSEQMAAosWBRQKEXON0GrHWkh3fBx4p0mdzUfyMA6vTzRBq8iwvh9gCRcSNUufVvOOL1129t7U/zQOBvrP9a9939KV1Oy6101MqsW6dHZCtp34eURK4c4sNJvX5fn3SrXHoStfcmSFkSP5fpR7aEfw+vwlpms/8tciBUwVuP2WqU0iZkViGPr8f9aVegsDLZwOGPqO3Phb/dfjm+Y5+LjzPQrN4o5fqtHjZigotLYPRJW/AA+Tp0RfvZUOzU6Lyd6tTWteDEzN4rp82XCVk8MMPnfxOTI0b69fprb9bv2DMGXBV9FzveGAwU//7N8fgtBRW9LKib6+fqbcStBtyJgsv7JA+IfA5eQDcVmFeI1S+8+0NqqHhpvmXBh17pP6hA7UFEogjN//oG5vbdh7Kswht1iNU6J7B4GRlUOZ90DIOg1sEG7hQoRh3EsTG6To=
  template:
    metadata:
      name: mattermost-minio-credentials
      namespace: mattermost
