---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-credentials
  namespace: mattermost
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgByczublTvg+sNK+Mh6d5Kq1C4orn90hXN5k8hMbOeeE1nffGCQntvXv0iWzgf6hAeyOWxWpIyzUYfO/oVCjfad276ex0NCV0IV/KY2Ws1/IgQaNTxXqZbHESFlu90/gO8Dc/XoBRB09vqWly95UQ9rjGQ3F/bzUraE4fSRisfwSX2FwTqvsC2i1rDELJO3YYZe1ZCXHwMt1yV5T6PTpY0cQaRfx9yjOM3Mfm4xCR3OYQjiz1pEEuqh17V/WkVdkIwucKah7FrJKXcCLQcA2EIv0oxmVxmUzxS6LAgisFWchXdMiQbVdBXW8Lmfh9TOnltPPMICf4ZoB8ebhdzT82VcmSYc5SQsNGdpSZe9J5vwpA1HQ/JktAWN9PjO7HM7cKgDXzq1/XEdKfvBKII6brGVWlw1MHKxtoA/rfsTYVMoFvWKA++hIcGFVX+XpCj4ZsowPlWkt0U2f8DeFBCXZMbeKStg/VtCwlyzDuZRDWCq1shFJlOsQuiMO3qmIG409rVqE0nFLsGkPb+MWcSrTaJ0QnZp6ahm3f8etU4KUGgqWx7+wjtqc10s65viE23JpiWEHNPb+UtNPJdVaofrLOxhwzVWIo5Ktmg1SSi1zEbBALrpIIGAKcQq8HefvOnPqqZ4ut+otaTd3NGh07qH6s6ktY3LfOMM7m57pwT9EwSdKrUfxlRq8fSqM/qJ885RsCxwP3OAopT5wzNNQeffuIkfqZYgxjrgcy/UJBtMRWfhW7LYrNiu2J+SKgMJ8uuhNo8O9kkn5maxBfTTfvPwd577Y9V1QVxYt7UbbGbOPWHJIN5biUd7mZaoPzgIy9TYJx3pRFhAtDi+RsZH95fGY4ZfD2Q4
  template:
    metadata:
      name: mattermost-db-credentials
      namespace: mattermost
