---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-credentials
  namespace: mattermost
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgB88lvGMBG3Cu1/s+iiZjnY0Todh7FuS1cr+lm0DndtQQKuBC5ZQq9QWM8JltiCMXSKHyW+KuRkur3MUQnohDGaZd5uojkcgpT6JtcwmVIka0uxaAHjDfIXAb2WZR0yJsbL/75mJZK0C3MTX930rlygV1ZUTxyX36SBbajHhSNNICbxhbp1RmL1eBS9YrAiYSW5ViTW5IqzUWUO3TRlK3U8Svhndc22a3Sj0SodbMHLJAxWRBnGzgTv3aZg4sNWMNuhbMRBh+bgCCwKxyPhJZPXm61xQlxKVms0b5EOOxIlSZEmLFtLMTupBgfrhx2oGhaN3iDEfo9D3S8jOzHPZsdH4EgG47LsnUmO9vFie9DsG+fvI3zuWhqPzGxUno4tY1jMYh1xySTa+sd/XYNtOQ6jj7HqomWFTkTGpD6IsS0kjF59kMQu1tsnPJYK6d8WD3FfjllLk5ET9G64OyiWxivVb+uh1/PZylHCXi9GszruVzPkLUn78oEeaMJWzssu6Bu0bMMdls+Ckx3mMbcIP47FdmGD+lfHXLYE4BOmYSjrqMcdIZMqOn9753C+b0VLtC16y43xeGKrCp6mH8phEPKI+bbfdmiIk/W5574L/WfkGe240G+PLJnV24mIi0oL6wChUArycI0jpQ3w9N6NAUWdcIYZGtyx6ulb55GjXNekEz/iFxD/Z8VJ2t1q8xEIrCuNQtqXrmEqz5z5xl5E4KzWiNIPUgSmmy4irvRrtW9gz5L8IdRZb6sioycgW5m1xSK4LvLPNOcunXqL4pseMaCWMrGrJwv/y1SdjqH5ZeVl6n2F+BfLgR4V9A6MR25Oh+uUNP9gGxOxAM9A2Jva42xPGxj1kaQSytV1mWeWfID00kxT+kdFtQ==
  template:
    metadata:
      name: mattermost-db-credentials
      namespace: mattermost
