---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-minio-credentials
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgA6wd1lTPB/FZvFg/GkEWN+yzP/is2hAONoGD9pmqisgMA1cjdOWnNef1/LNGsj83P8WBbp6trS10MDE/cX0vRtYqCZkoPouY135JYIMDQ8rQSfI9BeckieMbcLBqxXdbSmGnQSm/9ZdL4aMGAxYhi5mLDdDFb8ecnynYEGjLfaHPA43XM4aJ4TqUjCwyKsm5B539RzrzUfpoU02iVKT1u4aNNyvztFZWt4prMTIGc9GjcTH2w/1CRVBhc29KQfgT3mo2TSKt7YVqVnA8qwbWZwd7lN+GtbMwMDVfx+AvKvFQv0qMHttf2wegwO638Z6I2OXReV3OdGSzLqj2ITSYUE1sTAuc71Ha1OJrBYnbgtPfEtQ6kAm5WuAGu+vwKdtshs6N66j4N1BuKy8oB/Q0OYi6FKXrvtBPPobh8ejXbUGdJQGfKXVVpalmvLhbYvQ/e8wmduX3TkvnH1GMapcgBvYdHuqqotloVdvG2PFHkQ06GZeFenmtra45pjOxLdAom8h7ZcUHW3vE/V72ZsXnPfU4syGTv1cxmz8ZfH+9lG4bnvw4Sym3ZCf4psoQpuhDLgndU8tuHB78kZkooMoj2TJumpG74+/QwwK/BJ/ANSCdImDSGFR7nAQPdVvJMkH6iVL6eNUreOpXXsVPKMUto1t6fXryURjvsWFnamxByWswmM1dts+pfE5UgVGA/+gbhef51aT4jS8ceU9lyz8FLw
    secretkey: AgAMsmo+Gj+19bYLM7GbTKcEfEFePqOUEnNiQxwkMp8xXjd2T2Or22HsQ/kQmHVYVNrZWKrOIEYCBviZLFMybU9qbLYWxgauwMoA7+/mYvCP9bXk+yihjHjfRVf9EPsykSTWpz0gy9jUpw9qN+7g/9vRfqwm33ShdNsV4GIB2Xbfgv/vNHXz3jUcv4u35RZ/CqlxFbgREIBcWb1k3SE5NCtioWd3U8wBHyAa1UCbp2uO9V8zvsrMDfwIaOAaX7fCVs+EBPRQPPU+vHPauPqj58zAx4oRnc9RkUNNQGjyc/IVGKG2svPWbRb4LI/lAOIc6feLiZxRpQ1gnVXJrHf2erVVZbTa1KxuzkYuTapaxJddstUNUYPsBbo9LFkPi7RVAwz4MVls101b0xcrcPMNjmLC8UfbQk2NXT7O5EFH20Cjn2fG+V9oMTr6Jcn3YSwV9wFTJFFxdY6LfpShqDBGLEeodqhF+xA0Be+MF5aQugjH+EXxZ+a2945NTL9u5kitozjn3o8UBQ4iSpSWJC0KXy23z8ksLD8dDbxw72u15ktuPe+VOQTGP4WN1i5FCqNPMgr+DJrLaLSyprW6kdW6LTPDKDlLyy/Oh/qjyVL6AUKrln/vbxTZbcU66by++Mw+EKMEqZ1GYV/99uUq7GdqTt1p2iG+AthwlDxWER9RPH8Spy5lFIwtRNWG6xVGfwm2/JRuFrqKemTsDVpskgs=
  template:
    metadata:
      name: mattermost-minio-credentials
      namespace: mattermost
