---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-postgresql
  namespace: mattermost
spec:
  encryptedData:
    password: AgAtmfLEs960zUFiE/S+P55ADhlXCna81g32ObTSxVb0rwR/a0fqczCbke0N2LeQ3BpzDJDukFjn2gXgNtjCKa/ceH/pnm/qp7qdl/ADu8TTFlTGTJh/cUMw1ptyHwtSPa5ODEyyErIPWwXKJS+69wXHXzqGfLFUFNwNRUkm2tITI4Aknu8rufwOqIf8aMDKP3VWRE220TsGu+HAvEHfvD/D4i5ZsdjxnjHskueADaQrGP0DquoJKBnL5TP239K26GOemP4bZbp9YV7k2NIg7QmieXwkAtgHNiLH/Er7pmMgU41Ht8X78sCXBTh6zuEnwN2DFEreGdDCk8TLQbqEyy0hjUWgwENDJvDoxZ8pZtHRwPGShkbLUCMddHHnkJhrBwUPCfWTooQDK9fyq0YxjsVDYiOiKoowgSYI3KL6bhQcUduUtl5mqP11FYHwzD3vBT45bZn7vaLOT0nU4E4ATV+rc0n1R3wl+VBrnUixZoHaXmaYiiW54yP0McVdZGzJZYcoqBdJ0q296jSgGXuD7kFwR2ogGu0M/Um/LKNZg/m3wsiUFL+GHji9gEkmZ9gKRd+UGXcxsTumwkUKO9aa6OvfXSXLi9bBlUja/hg6qdfayefzgXejbjTMltm3n96t+DTJ9pJmAMJDY6b8HjSHEOVCW1HM4sz+0S6hSOj/Bo/mvtxsNQ8cu9+mCZWUQYQgJ23KyjcUe6YkWNHF+TvgjwCy9riftTHx3b1PJMd3Ckg=
    postgres-password: AgBMELZYOh09oSr4H15m1MH9gCWk09X9paTNkBbqZmxpYqkgc76MgIVuHa58oUK9tAqpGK7XkN7TqwUT/Tz59hDmr/CSCWgG+juq9ttHmhJcZSrM+fxuJSObzkzb933yFw1/S1tDATnTHr9Kbi2z0PwURPlUtpy+CieSGmZbKhAU/0T+GTUKEFUr9gHD0pHbWnw0s6KoRsCz+vQKBpuW78arWl5SNj8RY7a6mWBj9UWNYQPJGZsoGMTxNHyRzWQpPRPTNKfJcIsd80hbaar89ubwKJQ2gG6EzcDdpiXZ/7QB8Ws6e7AG+QQUAYXSJmyLHEkvup6uqRlDPvHL4WiDmVyPEIq4VqBh85vKrfQOnXSh/7XHvJN6Fg0YHwgAdFOnYBqnWUVuG2QFwWYnepmhzSPhtzEYFDk1BeJSpAMPOVf84L1m9lfJi8+DPidL4LdWXZVM0jlVKIGSyAk43fK+ejMPMoYOGQ0nQN3ku37ggho1ukFmmol61myLzfMvCmPUmFe8tcnW9HyZpK2b5uOiPDgFOlClHhBUtxfd5br1f/BDCjsTxXhSBv5R0/se6vCl6COAFowpa941UJJZvwj0agM0QlK+daCcIpyTWCoCBmkuofvjJCEPKftG5d5tt6QtgvxghQTFgwVNg9rnjVRKgJL9bnNX+mTJGcRINst/PDzf995AD7JpNOOLmgnWuHdvvN8mvnufvouN6FHgxFNidMVwJc5nmbEdUFTgHZsATDc=
  template:
    metadata:
      name: mattermost-db-postgresql
      namespace: mattermost
