---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-postgresql
  namespace: mattermost
spec:
  encryptedData:
    password: AgBVSHmctTs/M/3sU3cxErdC1g+hJOywdKr94KfD8P2ZVKSTJ/VirJoPiAEyL/p1u6Oidzpn6OpYVM0YLKugxqP/NrbmypWC7KvU/KQa0OxAVnErXR6RMyVMlnlazdJxnTx7I6aQDtP+WD1vxkgmI4nYwYkb/efOlxoiZ0Zf0Ts8wCWCYkbSQ8EYOwM5N4POuqLajzW0yPahaC4D0IgHDKYGZ5h8rehySZFnBNIr4uryBuNF1nl0C5lvCqCWd8CHA/iQxqHSrkbI41XrcwSuShjGSiDvTKUt4KMe45mdALFudyZEIIVIS194nSF8OkDFxQnouegELMKiiGAlTCYDw/S49/CS+W4wKRGaeUilKQ6/gHHyu6glCA5CVfRfgYIcGxfLlvXB0Db19bChQRsnYYlErcszEdnxh4zygg1lMfyfsNKEIJi56yumuhm2goSZI8b9/h0+VCAgK/iYk4I3lpcxWQ7W0+S1fYCLEEWrEeCP+T08tzhz08E3fMWRxHeV50GSfzx2FZDTIvv8sR6FI0ROFxHvkaHrT2pOd3gkLVvAZRgs1rH2pLce92TaDWLYsyXLZIwcyeKdBkc5RcxKftZ6DMlRVftikdrzgBXuO19BbZbkeUXqORJl0tISvEeKim4Hg/QG8y9YKGm2PvYcm1IcQP4ZphFAUS19eXWLtPWtdHU158IMnpsuGC1v94W4p04wGbU+EqzXVrjDyQ==
    postgres-password: AgB4Wc/NSQHwGnFDR9GM+M5NEPQdm99JoxuKn5PGgNwBY173UrNxP/oFjQA8x5Np6ZNZ54mpct7il5hnsQmLqbfsL7Ip/GaxIttRK0z7SuBTR6yy/pW1+2t5qaM7diZB8u3a8BB3yLHYvmjosgb6BJoJNArZIMQBrg/dTUjKQS4R451OL0ZWFBBXIPckfo+0M7r9qN6b/O+dWnpSPOfjR2hXd28aYXYrgKevKUTYiJsIC468axJ9xKL7OiI+2fCLFbJ5n4w64nNOJ9rAe0U1bSBCN69fuDXL0MclOsynuruukyrFcLSM77hKh4YhfnFmW9FiX1QmVqtBM62LsHhjoPVGEVNBJG+BFBTQIsdiEzV7VfX5vi1Asu2QbfHnSUKtldn1gpXslDrXe0yVl24iL4cl1O6VVE7pcjiR5GOsIXOqmUP4B8sqfwNtLocEV6bXHgnBqtDGiroN4t9AvV0quOSez5plVg2ThK53scIuap+ri4UmU1GwdYEB8L0X/lKTuMh9wTSsb2skvJuNlD6//aMzn3rS+sFHl8DK0XrvIPuzk0D9ZxOYd1swL6hKjyWKnruomOXdJ6BmzcCdahWd4VRVUd9HisjW6IktZ2Nm0j7uREERzBiFmy8TRX0B0Zb59UvWWMLXoFue4CkSzitaPwIS4mE/nOzrTay5DjRFaF0AhETI2cTOWSNFU+ahIT1iWQMPkVTCNGiTL30TMg==
  template:
    metadata:
      name: mattermost-db-postgresql
      namespace: mattermost
