---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-postgresql
  namespace: mattermost
spec:
  encryptedData:
    password: AgBLLO05J6/m628MdFk2pTHMQIF4LtfSvEOQoGpeRy3UQ/hJsRC6hYEmmQkWzoM2ovYNgJqwLREXaehUjEnQtA/xe2kJlT2klblkPmu7X2Cp35OGwu8JLM28zj2qFrYRoqmz3Js6YqaUJV5BNrU+nJ2gcKSby7ypdRBaPicG21K0YEaEX6t2F5czFw+PnCkC3A/sUKXALdnmP1LsBGGxLgGomzijWf1FAmPROnSDotJGq9OaGReN6oAbuq1jI7XKXSxCRC8/q5FQTNq0ZcK9wLjThvQ8nJdBvdDwBmQo3Yk3dHkafoxLnoycyKjfAZBdtJ8OHS4y2foLAm9KvUacyFWExqDeZeZ6yIeuMyWFAWsk60bbqm1ZSRQAPJwKi2KZgPOX1t5VMFdYXfO9xTUgvyZNob+Ue0sgiLLWRKvMje7ZCEDh5Ib2LTosP32aZsQ+AaIAHMlT4R/qpVYxlltG0WqjNnrt30Isv1XZ+g5Hh0vkE+gJG1XJKj1VNUWnNEqRvYCh4NNjsxSjFKHitI29rTfc2SeeIG+fMu5rTcAmEcZcdcT/EpBzAfU2eHx/EaXEYR7qBTS5RG2Xn/tBUx81cNXMoIG2Dl7hVmoz2UQykOXd8LRaKY7fSYsYkw2ij+Ibk3XGPCnlWQRy6veJUyuu9rFYt8MvUw5tKOCZ+lnT5YBpxmgPzr2HMnvzPB7aj5uir/g+SYeqUuck4nWYOg==
    postgres-password: AgBAl27nXs/xCdYBGx2h23BJ0+XSx38L2bg0dUgQmg8cmwQpIfzWlUbrg8/JVFHDjpaPuVg7rbQiazoFnOcBFIXrcnGlE4mufa4InnUJ54XV4QL2L7zxCO90DB88MBXTQwnAyOvdTXm/6EAhwrOF3Ge8I9GwrDdYQkRkoq+D8LcACIziVLBRoDgAeXUik8Xw3nj5rhfpm6PSqvNGiJkV1POp6sneIUpK+iVsU/5J8E6ALUV393UCmicTu+nHAa/8dm7YeSQRlnXyxGm7rcaMoIAFS+5NHLRMgW++eqSXbu79EUp9kqKY5tuAF4ZjdrSqfOm9Uf45ppYicT+HDkRFIvM2K/KobrwMZracb3bA3BbNT05LhPQH6340ysxrznxMXGmQbhfotINx1oXhi81dKoSioKeQv4TlDqg/38UR0F9Dw0gT201es2RAxqg/9Mj/H3a+P9/Or2i9EvhlGBn9OABnEDSToljlL0Ut1R5hi9p4EUjT6Vridq0suqpoKquE9g6hNaht8gzs+I/ybREVgMKrEtx46M8d1e6/JEFzUJqaFpoJSZnRC8wAYN7BpsaPFwwHLwjI40iV1F1y5uEcyZxBt6v57AeVthASOFZ+hz/g0+AXnolTU1xeraMkgX/tJUgalxvNkZXiYk6L5qoQyIN+XiuE4ZtVo2vQ8aJQTdQ1cGtm4+Pn6BzLVZKoXtuWaQvfnHh7nCjyBSHaKw==
  template:
    metadata:
      name: mattermost-db-postgresql
      namespace: mattermost
