---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-credentials
  namespace: mattermost
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgAu6UR7JFpBFpREQsrYJqCPzuDb02EalAz2+TLU5emxsHg7bkOZfolg4G0InWXxZpzMPfAhZ93JjblxnUkz/14aX17TRww4fcrEBSYZrebLtU1ot9E8/qLkZ+vA9IWBAylk4KhcLAOP1hyd3IfPciJwW3aWTf+2jCF/PnqX/3d4fMYQe3FGf47ag7eXN/8T14M5sD3Uuu3QezsgFHPZ74fbWt+ZcnQq8ff0y2zOMzY8vShZcqWif9njg92kmRrnYTl1D59k3Y0OoaAdOOf3fSHxm2h7OP/sH2E7MkgwLKqW7J+WTnXvWACH5dW3Yqa8rKLzF76nEwhvz+qX4hmBWMyy7TfKjsxHd084do0IOhJacxQAUHm9qQ29b9gZLba1T0tQQ70g2xp3F6bMJStIzUjMQfrMBz8hdQC4mfC9+fG6E3OScEzuKVpDe6XnnfoXGHvNYt96IjA6N9j74G1IEeF4ThW4LQOPj90C5XNGVg/GF18VKFqdgYKciw1qBWh5RC8I0LQqgpn4JfKyJJ11WDA2HNggCHuXT0oz7/zniR5oD1E2pPmeVMN6C8sBTTFFoaG5PaLeJdGWijxV1vffMtf+4mT7CXE2/4TXHhX0usmaIhxbv+8OCvVzIKpLEUzXYLAf8I49W6Fqv9ASlnyHTRF2co41dxUp5KMZNJS8yG5RSzQ3/mGv+g3SU+1Nhu6+vC0JMZt6ecozplbBPemAPN9GJhGMvnLZ8i4Dd6SVX48qOfalE6gaYc/GfZ1kCfyogXJbCjWVTzbxVspoSAz29rHF9d548X/Shm7Ei5x6lTTab7nX/apdl1ttPcig/CoLpeQM5pB5QiwMuB2q9QLwJGqb5AiU
  template:
    metadata:
      name: mattermost-db-credentials
      namespace: mattermost
