---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-minio-credentials
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgB4Y3cUKDPHbR7paudezCdXBocT/JrUsD0OKIT8QsaQZzcIBDclijLuK77qBjQ5OWBSwSEThPb5U2q8FssLaPoxoge+Qw4gSjYvMyoLwtF+NluSohxxoIlMx7ZESC4qMpM5PnbcR4RV2/r8ktEh7EdWRdPU3AypLTg0qwbwr1BzjzY91B2Pypv30NJgCLc8uyvAThM+iS7qRlsvJsF0zHXVsY8eexJi6N/N4dLYXRp86vFdCX/Ea1EvLVt0wQVCd4oifkL8RInTEJ4dSES8u9Z7/LQim//HWzbGbmZ1RWwXofmkotC3rC7CQLXR5YM56s2ilw6Q/esw8OyDRDSmcbGrpFSFY5xxE/oTgB6kC7zB0s9KWYZBkZTpicZRyMAqxsZJG/4VTe3jVJsTcI648K8Xg4+IyvOYEVywjccwQFeViQlkMRxN1aA4OFWLeXs0ae6V4g9UZFLylEEs/Hx61iS5pK5APswbShj+n2Glih9ekReSl3hmOvRWnXpCqe45cXt0k+xMIEaCouNy+VCAZ33IQGabY5UL0SBtm96hEUIpa+RNiuc6Gs8PIdFdHWxJLqea8nCy2pVRsd9FU79N8vKEh86gochJC/QL1Hn8DsHR5qMZ7hSqviuJ6RjQPS1CRkYxcAdMk4Hvnhbbb7PxngkCV88EINGU4Ow0I6SoQsRfSUoKsJOf7KkwndPvqgIb/ZPEC+Qr/+xbfsIBv+bFZ9s2
    secretkey: AgCfP8boQW4mIa7+9k87EQgOcxDfwSZQym43PJasLoq2XZVsZJ24vI6jimZfMgrpNxssghUOy521RmMVGj6n4/fMwAsROAvOFtwehfl6y1QW9XqPY3ZDBtuHdeND1JMtD6IS53lpGZehxIZ2npizh0PgmqFjr132WtKVHhy8GWMuxKUGEDMVtChfqZujhahNMwGjYpkw4y+zFEt10eg2OV8Tr+wmZFv0SBF18qnIeliX224rjNy468jtoknnEgOWGUWZWABFcKkO/5YAfeoxtkbZ88jDowVh9o2BYB432743cY8n8+LK2/zwRbpC804CSloSmLq1/ZfS6Pxi455ARkh/pvkSV+gfXNPJh5CLjb5tL9zwW1JNLBTaGwkWiyL+0h6v3NklLk1A7b094Anf53lL97jehwuTLsB1kjK4O0YVgHaF0cVgzhvPC0q+4MhlMPiu9q0RCEXGYPJM6L5N9kzE0NlmDvonsDfnnf4/t/OdhN18vOl7rMgdO8AdOGcJYpEndcPGLCQ90GxezvZNWa6PzxptKi5cWMQY+wo+QyMw5jY6wc4w2aCdR/fPXNPHk/J73wD6SQyPqBBnBXUkDJ+o4nNxAaU+eyguTQRKBNZNiEDBCTvAI9qqSlhox48kst7P6kEKjpxf8YTgz5aEnkio5mugdm6/hc2iiDb5iSVgO365k2l8esX9Yv85Jtxk5BVjU6PHC5WNYfUJEbA=
  template:
    metadata:
      name: mattermost-minio-credentials
      namespace: mattermost
