#!/usr/bin/env bash
# scripts/03-bootstrap-flux.sh
# Renders config, commits infra layer, runs flux bootstrap
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
load_env "$ROOT_DIR/.env"

log_section "03 — Bootstrap FluxCD"
require_tool flux
require_tool kubectl
require_tool git

kubectl cluster-info > /dev/null 2>&1 || {
  log_error "Cannot reach Kubernetes cluster."
  exit 1
}
log_ok "Cluster reachable"

# 1. Render cluster-config.yaml
log_step "Rendering clusters/production/cluster-config.yaml"
# SERVER_PRIVATE_IP: for kubeadm this was set by 02b-setup-kubeadm.sh.
# For kind it defaults to 127.0.0.1 (same as SERVER_IP in .env).
SERVER_PRIVATE_IP="${SERVER_PRIVATE_IP:-${SERVER_IP}}"

cat > "$ROOT_DIR/clusters/production/cluster-config.yaml" <<EOF
# AUTO-GENERATED by scripts/03-bootstrap-flux.sh — safe to commit
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-values
  namespace: flux-system
data:
  DOMAIN: "${DOMAIN}"
  SERVER_IP: "${SERVER_IP}"
  # SERVER_PRIVATE_IP: the IP actually assigned to the host's network interface.
  # On AWS EC2: this is the VPC private IP (e.g. 10.0.1.5).
  # On kind:    same as SERVER_IP (127.0.0.1).
  # Used by nginx-ingress externalIPs so kube-proxy routes cloud-NAT'd traffic to nginx.
  SERVER_PRIVATE_IP: "${SERVER_PRIVATE_IP}"
  LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
  CLUSTER_NAME: "${CLUSTER_NAME}"
EOF
log_ok "cluster-config.yaml rendered"

# 2. Render MetalLB IPAddressPool with correct IPv4 range
log_step "Rendering MetalLB IPAddressPool (range: ${METALLB_IP_RANGE})"
if [[ -z "${METALLB_IP_RANGE:-}" ]]; then
  log_error "METALLB_IP_RANGE is not set in .env. Run script 02a or 02b first."
  exit 1
fi
cat > "$ROOT_DIR/infrastructure/metallb-config/ipaddresspool.yaml" <<EOF
# AUTO-GENERATED by scripts/03-bootstrap-flux.sh — safe to commit
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - ${METALLB_IP_RANGE}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - default-pool
EOF
log_ok "MetalLB IPAddressPool rendered"

# 3. Commit infrastructure layer
log_step "Committing infrastructure layer to Git"
cd "$ROOT_DIR"

if [[ ! -d ".git" ]]; then
  git init
  git remote add origin "https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git"
fi

git add \
  clusters/ \
  infrastructure/ \
  apps/kustomization.yaml \
  apps/mattermost/namespace.yaml \
  apps/mattermost/kustomization.yaml \
  apps/mattermost/secrets/kustomization.yaml \
  kind/ \
  .gitignore \
  .env.example \
  README.md \
  bootstrap.sh \
  scripts/ 2>/dev/null || true

# Set git identity if not already configured (required for git commit)
git config user.email 2>/dev/null || git config user.email "${LETSENCRYPT_EMAIL:-deploy@noreply.local}"
git config user.name  2>/dev/null || git config user.name  "${GITHUB_USER:-flux-bootstrap}"

# Use authenticated remote URL for push (token not stored in commit history)
git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${GITHUB_REPO}.git" 2>/dev/null || true

git diff --cached --quiet && {
  log_info "Nothing new to commit"
} || {
  git commit -m "feat: add full infrastructure layer (sealed-secrets, metallb, nginx, cert-manager, mattermost-operator)"
  git push origin "${GITHUB_BRANCH}"
  # Reset to unauthenticated URL — token was only needed for the push
  git remote set-url origin "https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git" 2>/dev/null || true
  log_ok "Infrastructure layer committed and pushed"
}

# 4. Run flux bootstrap
log_step "Running flux bootstrap github"
flux bootstrap github \
  --owner="${GITHUB_USER}" \
  --repository="${GITHUB_REPO}" \
  --branch="${GITHUB_BRANCH}" \
  --path="clusters/${CLUSTER_NAME}" \
  --personal \
  --token-auth

log_ok "Flux bootstrapped"
git pull --rebase origin "${GITHUB_BRANCH}" 2>/dev/null || true

# 5. Apply cluster-values ConfigMap immediately
log_step "Applying cluster-values ConfigMap"
kubectl apply -f "$ROOT_DIR/clusters/production/cluster-config.yaml"
log_ok "cluster-values ConfigMap applied"

log_section "03 Complete"
echo "  FluxCD watching: https://github.com/${GITHUB_USER}/${GITHUB_REPO}"
echo "  Next: bash scripts/04-wait-and-seal.sh"
